.__tavern_ <-
structure(list(A = structure(1:103, .Label = c("Bawdy", "Beaming", 
"Beautiful", "Befuddled", "Black", "Blackened", "Blazing", "Bloody", 
"Blue", "Bright", "Brilliant", "Burning", "Chief", "Crooked", 
"Dancing", "Dandy", "Debaucherous", "Dragon's", "Duke's", "Elegant", 
"Empty", "Enchanted", "Extravagant", "Fabulous", "Fashionable", 
"Fat", "Fine", "Flamboyant", "Flying", "Gaudy", "Gilded", "Golden", 
"Grandiose", "Great", "Green", "Haunted", "Hearty", "Hidden", 
"Hungry", "Huntsman's", "Imposing", "Iron", "Jester's", "Jolly", 
"Lady's", "Laughing", "Lavish", "Little", "Lone", "Lord's", "Mad", 
"Magical", "Magnificent", "Marvelous", "Misty", "Noble", "Olde", 
"Opulent", "Ornate", "Pale", "Pleasant", "Posh", "Prodigal", 
"Purple", "Quiet", "Randy", "Ranger's", "Red", "Resplendent", 
"Rich", "Rusty", "Sacred", "Salty", "Scarlet", "Scarred", "Shoddy", 
"Silver", "Simple", "Skillful", "Sleeping", "Sleepy", "Small", 
"Sooty", "Splendid", "Splendiferous", "Staggering", "Steel", 
"Striking", "Subtle", "Sumptuous", "Ticklish", "Twisty", "Undefeated", 
"Unknown", "Unseen", "Wayward", "White", "Wicked", "Wild", "Wistful", 
"Witch's", "Wizard's", "Yellow"), class = "factor"), B = structure(c(1L, 
2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L, 11L, 12L, 13L, 14L, 15L, 
16L, 17L, 18L, 19L, 20L, 21L, 22L, 23L, 24L, 25L, 26L, 27L, 28L, 
29L, 30L, 31L, 32L, 33L, 34L, 35L, 36L, 37L, 38L, 39L, 40L, 41L, 
42L, 43L, 44L, 45L, 46L, 47L, 48L, 49L, 50L, 51L, 52L, 53L, 54L, 
55L, 56L, 56L, 57L, 58L, 59L, 60L, 61L, 62L, 63L, 64L, 65L, 66L, 
67L, 68L, 69L, 70L, 71L, 72L, 73L, 74L, 75L, 76L, 77L, 78L, 79L, 
80L, 81L, 82L, 83L, 84L, 85L, 86L, 87L, 88L, 89L, 90L, 91L, 92L, 
93L, 94L, 95L, 96L, 97L, 98L, 99L, 100L, 101L, 102L), .Label = c("Apple", 
"Arrow", "Backside", "Bell", "Blade", "Boozer", "Bow", "Brew", 
"Candle", "Cask", "Cat", "Centaur", "Cloak", "Courtesan", "Cow", 
"Crook", "Crossing", "Cup", "Dagger", "Deceiver", "Demon", "Devil", 
"Dew", "Dewdrop", "Drunk", "Drunkard", "Ear", "Feast", "Fire", 
"Flask", "Floozy", "Folly", "Fool", "Fop", "Forest", "Friar", 
"Ghost", "Goblet", "Grave", "Guzzler", "Hand", "Harlequin", "Harlot", 
"Harp", "Harper", "Heartbreaker", "Hearth", "Helm", "Hideaway", 
"Horn", "Hound", "Hussy", "Hustler", "Keg", "Kettle", "Key", 
"Knife", "Knight", "Lagoon", "Lizard", "Lush", "Mage", "Monk", 
"Mug", "Oak", "Ogre", "Orc", "Oven", "Ox", "Philanderer", "Phoenix", 
"Pint", "Priest", "Quill", "Rain", "Reprobate", "Satyr", "Seducer", 
"Shield", "Sot", "Staff", "Steed", "Strumpet", "Tart", "Thief", 
"Tickle", "Tinker", "Tooth", "Tramp", "Transient", "Treasure", 
"Troll", "Trollop", "Unicorn", "Vagabond", "Vagrant", "Wand", 
"Wheel", "Whistle", "Whore", "Wolf", "Yoke"), class = "factor"), 
    C = structure(c(2L, 3L, 4L, 5L, 6L, 8L, 7L, 9L, 10L, 11L, 
    12L, 13L, 14L, 15L, 16L, 17L, 18L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L), .Label = c("", "Alehouse", "Barroom", 
    "Brewhouse", "Canteen", "Drinkery", "Groghouse", "Grog Shop", 
    "Lounge", "Meadhall", "Pub", "Public House", "Saloon", "Speakeasy", 
    "Taphouse", "Taproom", "Tavern", "Watering Hole"), class = "factor")), .Names = c("A", 
"B", "C"), class = "data.frame", row.names = c(NA, -103L))



.__town_ <-
structure(list(H1 = structure(c(2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 
10L, 11L, 12L, 13L, 14L, 15L, 16L, 17L, 18L, 19L, 20L, 21L, 22L, 
23L, 24L, 25L, 26L, 27L, 28L, 29L, 30L, 31L, 32L, 33L, 34L, 35L, 
36L, 37L, 38L, 39L, 40L, 41L, 42L, 43L, 44L, 45L, 46L, 47L, 48L, 
49L, 50L, 51L, 52L, 53L, 54L, 55L, 56L, 57L, 58L, 59L, 60L, 61L, 
62L, 63L, 64L, 65L, 66L, 67L, 68L, 69L, 70L, 71L, 72L, 73L, 74L, 
75L, 76L, 77L, 78L, 79L, 80L, 81L, 82L, 83L, 84L, 85L, 86L, 87L, 
88L, 89L, 90L, 91L, 92L, 93L, 94L, 95L, 96L, 97L, 98L, 99L, 100L, 
101L, 102L, 103L, 104L, 105L, 106L, 107L, 108L, 109L, 110L, 111L, 
112L, 113L, 114L, 115L, 116L, 117L, 118L, 119L, 120L, 121L, 122L, 
123L, 124L, 125L, 126L, 127L, 128L, 129L, 130L, 131L, 132L, 133L, 
134L, 135L, 136L, 137L, 138L, 139L, 140L, 141L, 142L, 143L, 144L, 
145L, 146L, 147L, 148L, 149L, 150L, 151L, 152L, 153L, 154L, 155L, 
156L, 157L, 158L, 159L, 160L, 161L, 162L, 163L, 164L, 165L, 166L, 
167L, 168L, 169L, 170L, 171L, 172L, 173L, 174L, 175L, 176L, 177L, 
178L, 179L, 180L, 181L, 182L, 183L, 184L, 185L, 186L, 187L, 188L, 
189L, 190L, 191L, 192L, 193L, 194L, 195L, 196L, 197L, 198L, 199L, 
200L, 201L, 202L, 203L, 204L, 205L, 206L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L
), .Label = c("", "Aber", "Albi", "Als", "Alv", "Arth", "Asger", 
"Asta", "Ayles", "Badens", "Bal", "Ban", "Bas", "Bath", "Bed", 
"Bell", "Birch", "Birm", "Bladen", "Bland", "Blud", "Blyth", 
"Borg", "Borst", "Bran", "Brent", "Brid", "Bur", "Burn", "Cam", 
"Canter", "Carl", "Chant", "Chat", "Chel", "Cherry", "Chill", 
"Claren", "Clover", "Cob", "Col", "Cor", "Cos", "Cot", "Crew", 
"Dag", "Deer", "Dragon", "Dulci", "Dun", "East", "Ein", "El", 
"Ever", "Ext", "Fal", "Fleet", "Foggy", "Fol", "Frey", "Frost", 
"Gal", "Gallo", "Gate", "Glast", "Green", "Gren", "Grey", "Grim", 
"Grin", "Ha", "Hal", "Har", "Hasle", "Haver", "Hay", "Helge", 
"Hels", "Hem", "Hemp", "Herne", "Hess", "High", "Hook", "Horn", 
"Hors", "Hum", "Hunt", "Hús", "Idyl", "Ilfra", "Ingle", "Ips", 
"Is", "Janis", "Jen", "Jørgen", "Jut", "Kel", "Kell", "Ket", 
"Kings", "Kins", "Kirk", "Leech", "Leo", "Lily", "Linden", "Lithe", 
"Lor", "Low", "Ly", "Mack", "Maid", "Mal", "Mans", "Mar", "Mel", 
"Mickles", "Mid", "Middle", "Mil", "Min", "Mon", "Mot", "Nala", 
"New", "Nim", "Nîm", "Nord", "North", "Nott", "Nov", "Nunea", 
"Oak", "Ob", "Od", "Ok", "Old", "Olf", "Orv", "Peter", "Ponty", 
"Ports", "Raven", "Ria", "Rose", "Roth", "Rova", "Rowan", "Sax", 
"Scar", "Scriv", "Scunk", "Sev", "Shef", "Sheg", "Sher", "Shrew", 
"Siga", "Skald", "Skeg", "Skeld", "Skell", "Smithy", "Stag", 
"Stam", "Stan", "Stav", "Stock", "Storm", "Strat", "Stroud", 
"Suf", "Swan", "Sweet", "Tar", "Tet", "Thorn", "Throck", "Timble", 
"Tinta", "Tir", "Trow", "Tua", "Tun", "Turn", "Ty", "Ulf", "Umber", 
"Vairn", "Vol", "Ware", "Warn", "Welk", "Wes", "Wester", "Win", 
"Wit", "Wolf", "Wor", "Wulf", "Wy", "Wyrm", "Yar", "Yeo"), class = "factor"), 
    H2 = structure(1:258, .Label = c("acrest", "age", "andia", 
    "ania", "anium", "app", "berg", "berga", "berk", "björg", 
    "bog", "borough", "bourne", "bran", "bray", "bridge", "burg", 
    "bury", "castle", "chaple", "chase", "chester", "cliffe", 
    "combe", "copse", "cove", "crest", "cross", "crossing", "dale", 
    "dare", "dburn", "dcove", "deen", "deep", "dell", "den", 
    "denheath", "dennios", "denwold", "dfara", "dfield", "dlegårda", 
    "dlelanden", "dley", "don", "ell", "emarch", "emiri", "enell", 
    "eness", "enios", "entiga", "erentry", "erfara", "ergarth", 
    "erhall", "erley", "erow", "erstóll", "faire", "feld", "fell", 
    "field", "firth", "fjord", "flea", "flói", "föld", "folk", 
    "foote", "for", "ford", "forth", "foss", "gard", "gård", 
    "gårda", "gärde", "garden", "garth", "gate", "gerd", "gill", 
    "glen", "gorm", "govia", "gród", "grove", "guard", "hall", 
    "halla", "ham", "harbor", "haven", "head", "heath", "hill", 
    "hold", "holm", "huld", "hult", "hyberga", "iage", "inberk", 
    "inbran", "ing", "ington", "innish", "invald", "inweald", 
    "iopolis", "isle", "kapp", "keep", "kerne", "knoll", "köping", 
    "laig", "land", "landa", "landen", "landy", "leigh", "lerentry", 
    "lerfara", "lerstóll", "ley", "lflea", "lhead", "lo", "lock", 
    "locke", "loleigh", "lond", "lösa", "lowe", "lrill", "march", 
    "mark", "market", "meade", "meara", "mere", "mill", "minster", 
    "mir", "miri", "moor", "nbourne", "nell", "ness", "nia", 
    "nios", "nock", "north", "nvern", "nway", "nweald", "ock", 
    "onia", "-on-sea", "-on-the-river", "öping", "opoli", "opolis", 
    "poole", "psten", "pwood", "reach", "reve", "rhaven", "riburg", 
    "rill", "rmfirth", "rovia", "row", "rowton", "rriburg", "rrowton", 
    "rström", "rtstad", "run", "sberk", "scopse", "sea", "sfirth", 
    "sforth", "sgard", "sgill", "sham", "sheath", "shift", "shill", 
    "shire", "shroud", "sivar", "slebury", "slond", "smoor", 
    "snios", "snock", "srill", "ssea", "sshire", "sstead", "sstock", 
    "stable", "stad", "stat", "stead", "sten", "stock", "stóll", 
    "ston", "stone", "ström", "sund", "sward", "swell", "terlowe", 
    "tföld", "thorpe", "tiga", "ton", "tower", "tstad", "vald", 
    "vale", "varn", "varna", "veld", "verania", "verberga", "verbury", 
    "vergard", "verholm", "verndon", "vernfara", "vernfoote", 
    "verning", "vik", "vil", "ville", "wald", "ward", "way", 
    "weald", "well", "wich", "wick", "wild", "wilda", "wold", 
    "wood", "wright", "wyn", "ywilda"), class = "factor"), D1 = structure(c(13L, 
    3L, 14L, 10L, 16L, 4L, 17L, 8L, 7L, 5L, 15L, 2L, 6L, 11L, 
    12L, 9L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L), .Label = c("", "Bara", "Bil", "Bun", 
    "Gil", "Gun", "Khath", "Ki", "Mor", "Nul", "Shar", "Shun", 
    "Tumun", "Un", "Zadd", "Zanul", "Zarakh"), class = "factor"), 
    D2 = structure(c(14L, 18L, 11L, 8L, 10L, 3L, 16L, 5L, 17L, 
    2L, 15L, 13L, 6L, 4L, 7L, 12L, 9L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), .Label = c("", "barak", 
    "biln", "bundush", "buzir", "dabar", "dablin", "dar", "dun", 
    "edzan", "gila", "ia", "inal", "munz", "ola", "ula", "zah", 
    "zir"), class = "factor"), E1 = structure(c(6L, 13L, 21L, 
    12L, 7L, 2L, 18L, 19L, 5L, 14L, 3L, 11L, 22L, 4L, 9L, 17L, 
    20L, 8L, 16L, 10L, 15L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L), .Label = c("", "Adhor", "Amar", "Bar", "Bel", 
    "Brasir", "Brego", "Dol", "El", "For", "Gion", "Gul", "Harl", 
    "Imrar", "Lion", "Lum", "Nargo", "Nion", "O", "Sir", "Thar", 
    "Vall"), class = "factor"), E2 = structure(c(4L, 16L, 2L, 
    19L, 8L, 9L, 3L, 7L, 15L, 22L, 10L, 11L, 13L, 18L, 14L, 17L, 
    5L, 12L, 6L, 21L, 20L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L), .Label = c("", "ade", "adhell", "asea", "erast", 
    "eren", "geladh", "griath", "gul", "iest", "imiron", "ithmal", 
    "lin", "lond", "onde", "one", "orast", "orest", "sea", "thriad", 
    "thriand", "thrith"), class = "factor"), HL1 = structure(c(2L, 
    3L, 4L, 5L, 7L, 10L, 11L, 12L, 13L, 14L, 15L, 16L, 17L, 18L, 
    19L, 21L, 22L, 23L, 24L, 25L, 26L, 27L, 29L, 30L, 31L, 32L, 
    33L, 34L, 35L, 36L, 8L, 6L, 9L, 20L, 28L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), .Label = c("", "Ar", 
    "Ars", "Ash", "Be", "Bramble", "Bre", "Briar", "Bush", "By", 
    "Ca", "Chea", "Co", "Coa", "Cu", "Day", "En", "Fy", "Hai", 
    "Hobbi", "Hoe", "Ke", "Pee", "Po", "Pour", "Ra", "Se", "Shire", 
    "Stry", "The", "Tray", "Tre", "Wa", "Wee", "Wye", "Yer"), class = "factor"), 
    HL2 = structure(c(2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L, 11L, 
    12L, 13L, 14L, 15L, 16L, 17L, 18L, 19L, 20L, 21L, 22L, 24L, 
    25L, 26L, 2L, 3L, 6L, 7L, 8L, 9L, 10L, 12L, 15L, 16L, 17L, 
    21L, 23L, 24L, 26L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), .Label = c("", 
    "bluff", "brook", "bury", "don", "falls", "field", "ford", 
    "gate", "grove", "heath", "hill", "ley", "minster", "moor", 
    "peak", "pool", "shire", "stead", "ston", "stone", "thorp", 
    "ton", "valley", "wich", "wood"), class = "factor")), .Names = c("H1", 
"H2", "D1", "D2", "E1", "E2", "HL1", "HL2"), class = "data.frame", row.names = c(NA, 
-258L))



.__drink_ <-
structure(list(D = structure(c(12L, 13L, 4L, 9L, 10L, 11L, 3L, 
6L, 5L, 2L, 1L, 8L, 7L), .Label = c("bottle of bigbeard's cider", 
"bottle of bitter black", "bottle of bloodwine", "bottle of dewdrop ale", 
"bottle of dragon's breath", "bottle of dwarven spice rum", "bottle of gnomish mead", 
"bottle of goblin stout", "bottle of kobold dragonbrew", "bottle of ogre brine", 
"bottle of potato spirits", "bottle of stonewhiskey", "bottle of winter wine"
), class = "factor")), .Names = "D", class = "data.frame", row.names = c(NA, 
-13L))



.__food_ <-
structure(list(F = structure(c(28L, 13L, 1L, 5L, 17L, 27L, 19L, 
10L, 15L, 12L, 16L, 21L, 4L, 11L, 14L, 23L, 6L, 26L, 18L, 2L, 
9L, 24L, 7L, 3L, 22L, 8L, 25L, 20L), .Label = c("apple", "bag of cashews", 
"bag of raspberries", "baguette", "bottle of honey", "carrots", 
"cloves of garlic", "cucumber", "dried figs", "dried meat", "dwarven blackbread", 
"elven waybread", "hard boiled egg", "hardtack", "jerkey", "links of sausage", 
"onion", "pouch of almonds", "pouch of mushrooms", "pouch of raisins", 
"pouch of spicy peppers", "pouch of strawberries", "pretzel", 
"salted fish", "small jar of pickles", "stick of yak butter", 
"turnip", "wedge of Cheese"), class = "factor")), .Names = "F", class = "data.frame", row.names = c(NA, 
-28L))



.__gems_ <-
structure(list(A = structure(c(14L, 13L, 19L, 7L, 20L, 4L, 3L, 
9L, 6L, 11L, 5L, 18L, 17L, 15L, 21L, 8L, 10L, 12L, 16L, 2L, 1L
), .Label = c("", "aqua turquoise with darker mottling", "blue eye agate", 
"brown eye agate", "dark blue lapis lazuli with yellow fecks", 
"gray-black hematite", "gray eye agate", "gray-green moss agate", 
"green circles eye agate", "jet black obsidian", "light blue lapis lazuli", 
"light pink rhodochrosite", "mottled deep blue azurite", "opaque azurite", 
"pink moss agate", "rich golden brown tiger eye agate with dark striping", 
"striated dark green malachite", "striated light green malachite", 
"transparent pale blue quartz", "white eye agate", "yellow-white moss agate"
), class = "factor"), B = structure(c(8L, 11L, 13L, 18L, 16L, 
12L, 3L, 1L, 19L, 2L, 20L, 10L, 7L, 17L, 14L, 9L, 21L, 5L, 4L, 
15L, 6L), .Label = c("black jasper", "black onyx", "blue jasper", 
"blue smoky quartz", "brown smoky quartz", "clear pale aqua zircon", 
"clear rock crystal", "dark gray bloodstone with red flecks", 
"light gray smoky quartz", "onyx with black and white bands", 
"orange carnelian", "pale yellow-brown citrine", "Red-brrown carnelian", 
"sardonyx with red and white bands", "smoky star rose quartz with white star center", 
"translucent emerald green chrysoprase", "transparent rock crystal", 
"white chalcedony", "white moonstone with pale blue hue", "white onyx", 
"yellow smoky quartz"), class = "factor"), C = structure(c(18L, 
5L, 14L, 9L, 20L, 12L, 4L, 8L, 10L, 6L, 19L, 7L, 13L, 11L, 2L, 
3L, 17L, 16L, 15L, 1L, 1L), .Label = c("", "blue tourmaline", 
"brown tourmaline", "crimson coral", "dark green alexandrite", 
"dark green jade", "deep black jet", "deep red garnet", "green chrysoberyl", 
"light green jade", "pale green tourmaline", "pink coral", "pure white pearl", 
"purple crystal amethyst", "Red-brown spinel", "red spinel", 
"red tourmaline", "transparent golden amber", "white jade", "Yellow-green chrysoberyl"
), class = "factor"), D = structure(c(7L, 9L, 8L, 2L, 6L, 5L, 
3L, 4L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), .Label = c("", 
"black pearl", "deep blue spinel", "golden yellow topaz", "green spinel", 
"olive green peridot", "pale blue-green aquamarine", "rose pearl", 
"violet crystal garnet"), class = "factor"), E = structure(c(3L, 
5L, 8L, 4L, 6L, 2L, 7L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L), .Label = c("", "clear sapphire", "Dark green black opal with black mottling and golden flecks", 
"deep purple oriental amethyst", "fiery red fire opal", "fiery yellow oriental topaz", 
"medium blue sapphire", "pale blue opal with green and gold mottling"
), class = "factor"), F = structure(c(8L, 4L, 9L, 12L, 7L, 3L, 
6L, 2L, 5L, 11L, 10L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), .Label = c("", 
"bright green oriental emerald", "brilliant green emerald", "clear blue-white diamond", 
"deep crimson red ruby", "fiery orange jacinth", "poink diamond", 
"rich black sapphire", "rich blue diamond", "translucent blue sapphire with white star highlights", 
"translucent ruby with white star highlights", "yellow diamond"
), class = "factor")), .Names = c("A", "B", "C", "D", "E", "F"
), class = "data.frame", row.names = c(NA, -21L))



.__jewelry_ <-
structure(list(J = structure(c(8L, 7L, 2L, 5L, 6L, 3L, 4L, 9L, 
1L), .Label = c("bracelet", "brooch", "earring", "locket", "necklace", 
"pendant", "ring", "signet ring", "torc"), class = "factor")), .Names = "J", class = "data.frame", row.names = c(NA, 
-9L))



.__mundane_ <-
structure(list(scraps.of.bad.poetry = structure(c(15L, 16L, 8L, 
3L, 7L, 18L, 6L, 2L, 13L, 12L, 5L, 10L, 11L, 9L, 14L, 1L, 17L, 
4L), .Label = c("1d6 colorful pebbles", "bent nails", "blob of wax", 
"block of lard soap", "bloody rag", "bottle cork", "candle", 
"dirty handkerchief", "jar of urine", "lock of hair", "page torn from a book", 
"personal letter", "pouch of sand", "set of wooden false teeth", 
"shark's tooth", "shopping list", "small sack", "wooden comb"
), class = "factor"), box.of.chalk = structure(c(9L, 7L, 12L, 
16L, 11L, 13L, 2L, 10L, 14L, 4L, 6L, 15L, 3L, 8L, 5L, 1L, 1L, 
1L), .Label = c("", "1d3 incense sticks", "1d4 fishhooks", "1d6 feet of string", 
"2d6 blank papyrus scrolls", "bone tweezers", "cloth cap", "empty glass bottle", 
"empty waterskin", "fancy quill", "iron pliers", "sewing needles", 
"small glass jar", "small iron box", "small wooden mallet", "spools of thread"
), class = "factor"), flask.of.oil = structure(c(6L, 11L, 7L, 
13L, 9L, 10L, 4L, 14L, 3L, 2L, 15L, 5L, 12L, 8L, 1L, 1L, 1L, 
1L), .Label = c("", "1d4 feet of rope", "1d5 bandages", "3d4 foolsgold pieces", 
"empty small pouch", "flint and steel", "lacy undergarments", 
"merchant's scale", "metal file", "oxbone scissors", "pair of cloth gloves", 
"small hourglass", "small torch", "steel folding knife", "whetstone"
), class = "factor"), compass..d8.gp. = structure(c(8L, 9L, 3L, 
4L, 2L, 11L, 10L, 6L, 5L, 7L, 12L, 1L, 1L, 1L, 1L, 1L, 1L, 1L
), .Label = c("", "deerskin gloves", "drafting compass", "glass cutter", 
"grappling hook", "leather belt", "poor lock", "signal whistle", 
"steel mirror (d4 gp)", "thief's tools", "tinder box", "vial of writing ink"
), class = "factor"), crystal.prism = structure(c(4L, 5L, 3L, 
2L, 6L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), .Label = c("", 
"magnifying glass", "silver bell", "silver handmirror", "tiny music box", 
"vial of perfume"), class = "factor")), .Names = c("scraps.of.bad.poetry", 
"box.of.chalk", "flask.of.oil", "compass..d8.gp.", "crystal.prism"
), class = "data.frame", row.names = c(NA, -18L))



.__potions_ <-
structure(list(A = structure(c(1L, 6L, 2L, 5L, 3L, 4L, 3L, 4L
), .Label = c("bless", "climbing", "cure minor wounds (2)", "minor healing (1d3+1)", 
"oil of fumbling", "slow poison"), class = "factor"), B = structure(c(3L, 
4L, 8L, 5L, 2L, 7L, 6L, 1L), .Label = c("", "cold resistance", 
"cure light wounds (1d8)", "dispel magic", "fire resistance", 
"healing (2d4+2)", "invisibility", "madness"), class = "factor"), 
    C = structure(c(2L, 5L, 6L, 3L, 4L, 7L, 1L, 1L), .Label = c("", 
    "cure moderate wounds (2d8)", "diminution", "levitation", 
    "neutralize poison", "remove curse", "slipperiness"), class = "factor"), 
    D = structure(c(3L, 2L, 7L, 4L, 5L, 6L, 1L, 1L), .Label = c("", 
    "cure blindness", "cure serious wounds (3d8)", "giant strength", 
    "speed", "vitality", "youth"), class = "factor"), E = structure(c(6L, 
    5L, 3L, 2L, 4L, 1L, 1L, 1L), .Label = c("", "cure critical wounds (4d8)", 
    "dragon control", "extra-healing (3d8+3)", "invulnerability", 
    "longevity"), class = "factor")), .Names = c("A", "B", "C", 
"D", "E"), class = "data.frame", row.names = c(NA, -8L))



.__pot_desc_ <-
structure(list(Taste = structure(c(88L, 2L, 3L, 4L, 5L, 6L, 7L, 
8L, 9L, 10L, 11L, 12L, 13L, 14L, 15L, 18L, 16L, 17L, 19L, 20L, 
21L, 22L, 23L, 24L, 25L, 26L, 27L, 28L, 29L, 30L, 31L, 32L, 33L, 
34L, 35L, 36L, 37L, 38L, 39L, 40L, 41L, 42L, 43L, 44L, 45L, 46L, 
47L, 48L, 49L, 50L, 51L, 52L, 53L, 54L, 55L, 56L, 57L, 58L, 59L, 
60L, 61L, 62L, 64L, 63L, 65L, 66L, 67L, 68L, 69L, 70L, 71L, 72L, 
73L, 74L, 75L, 76L, 77L, 78L, 79L, 79L, 80L, 81L, 82L, 83L, 84L, 
85L, 86L, 87L, 89L, 90L, 91L, 92L, 93L, 94L, 95L, 96L, 97L, 98L, 
99L, 100L, 1L, 1L, 1L, 1L, 1L), .Label = c("", " Acrid", " Alcohol", 
" Ale", " Almond", " Ammonia", " Apple", " Ashes", " Bacon", 
" Banana", " Beef", " Blueberry", " Brain-Numbingly Sour", " Brine", 
" Butter", " Buttered Toast", " Buttermilk", " Butter Rum", " Carrot", 
" Cheese", " Cherry", " Chocolate", " Cinnamon", " Citrus", " Coconut", 
" Compost", " Copper", " Corn", " Curry", " Dung", " Fish", " Flour", 
" Flowers", " Fresh Baked Bread", " Garlic", " Gasoline", " Ginger", 
" Grape", " Grass", " Gravy", " Green Tea", " Hard Cider", " Hot Pepper", 
" Ink", " Leather", " Licorice", " Lime", " Maple Syrup", " Mesquite", 
" Metallic", " Mildew", " Milk", " Moldy Bread", " Moth Balls", 
" Mushrooms", " Nacho Cheese", " Orange", " Paprika", " Passion Fruit", 
" Pear", " Pepper", " Peppermint", " Pineapple", " Pine Tar", 
" Pork", " Potato", " Poultry", " Pumpkin", " Raw Meat", " Roofing Tar", 
" Rot and Decay", " Rotten Apple", " Rotten Meat", " Rotten Vegetables", 
" Rum", " Rusty Metal", " Rye Bread", " Sand", " Shrimp", " Sickeningly Sweet", 
" Sour Apple", " Sour Milk", " Spearmint", " Strawberry", " Sugar", 
" Sweat", " Tart Cherry", " Tasteless/Odorless", " Thyme", " Tomato", 
" Urine", " Vanilla", " Vinegar", " Vodka", " Wasabi", " Watercress", 
" Wax", " Wet Earth", " Whipped Cream", " Wood"), class = "factor"), 
    Container = structure(c(6L, 4L, 10L, 12L, 9L, 2L, 8L, 13L, 
    5L, 11L, 3L, 14L, 7L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), .Label = c("", "Bottle", 
    "Ceramic pyramid", "Crock", "Crystal Decanter", "Flask", 
    "Iron tube", "Jar", "Jug", "Pot", "Skull", "Stein", "Vial", 
    "Water skin"), class = "factor"), Label = structure(c(4L, 
    3L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), .Label = c("", 
    "Correct", "Incorrect", "None"), class = "factor"), Label.Language = structure(c(3L, 
    4L, 2L, 6L, 5L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), .Label = c("", 
    "Common", "Dwarven", "Elvish", "Gnome", "Halfling"), class = "factor"), 
    Color = structure(c(2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 12L, 
    10L, 11L, 13L, 14L, 15L, 16L, 17L, 18L, 19L, 20L, 21L, 22L, 
    23L, 24L, 25L, 26L, 27L, 28L, 29L, 30L, 31L, 32L, 33L, 34L, 
    35L, 36L, 37L, 38L, 39L, 40L, 41L, 42L, 43L, 44L, 45L, 46L, 
    47L, 48L, 49L, 50L, 51L, 52L, 53L, 54L, 55L, 56L, 57L, 58L, 
    59L, 60L, 61L, 62L, 63L, 64L, 65L, 66L, 67L, 68L, 69L, 70L, 
    71L, 72L, 73L, 74L, 75L, 76L, 77L, 78L, 79L, 81L, 80L, 82L, 
    83L, 84L, 85L, 86L, 87L, 88L, 89L, 90L, 91L, 92L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), .Label = c("", 
    " Apple Green", " Aqua Blue", " Aquamarine", " Avocado Green", 
    " Beige", " Black", " Blood Red", " Blue", " Blue-Brown", 
    " Blue-Green", " Blue Grey", " Brown-Grey", " Burnt Ochre", 
    " Burnt Umber", " Canary Yellow", " Cerulean Blue", " Chartreuse", 
    " Cherry-Blossom Pink", " Chestnut Brown", " Colorless", 
    " Cornflower Blue", " Crimson", " Dark Blue", " Dark Brown", 
    " Dark Green", " Dark Grey", " Dark Orange", " Dark Purple", 
    " Dark Red", " Dusty Rose", " Electric Blue", " Emerald Green", 
    " Fluorescent Green", " Fluorescent Orange", " Fluorescent Yellow", 
    " Forest Green", " Golden Yellow", " Grass Green", " Green-Brown", 
    " Gunmetal Blue", " Heliotrope Purple", " Hot Pink", " Indigo Blue", 
    " Iron Grey", " Ivory", " Kelly Green", " Lavender", " Lemon Yellow", 
    " Light Blue", " Lilac", " Lime Green", " Magenta", " Maroon", 
    " Mauve", " Melon Pink", " Metallic Bronze", " Metallic Copper", 
    " Metallic Gold", " Metallic Silver", " Midnight Purple", 
    " Mint Green", " Mushroom White", " Olive Green", " Orange", 
    " Orange-Brown", " Pale Yellow", " Pastel Blue", " Pastel Green", 
    " Pastel Purple", " Pastel Yellow", " Peach", " Poppy Red", 
    " Powder Blue", " Prussian Blue", " Pumpkin Orange", " Purple", 
    " Raw Umber", " Red", " Reddish Brown", " Red-Orange", " Rose Pink", 
    " Royal Blue", " Royal Purple", " Shit Brown", " Silver Gray", 
    " Turquoise", " Violet", " White", " Yellow", " Yellow Green", 
    " Yellow-Orange"), class = "factor"), Extra = structure(c(8L, 
    10L, 1L, 2L, 3L, 4L, 5L, 6L, 7L, 9L, 11L, 12L, 13L, 14L, 
    15L, 16L, 17L, 18L, 19L, 20L, 28L, 23L, 24L, 21L, 22L, 26L, 
    27L, 25L, 32L, 29L, 31L, 30L, 33L, 35L, 34L, 36L, 37L, 38L, 
    39L, 40L, 41L, 42L, 43L, 44L, 45L, 46L, 47L, 48L, 52L, 51L, 
    49L, 53L, 54L, 57L, 58L, 59L, 60L, 50L, 61L, 62L, 63L, 64L, 
    65L, 66L, 67L, 68L, 70L, 69L, 71L, 73L, 72L, 74L, 75L, 76L, 
    77L, 78L, 79L, 81L, 82L, 80L, 84L, 83L, 85L, 86L, 87L, 88L, 
    89L, 92L, 90L, 91L, 93L, 94L, 95L, 96L, 97L, 98L, 99L, 100L, 
    102L, 101L, 103L, 104L, 105L, 55L, 56L), .Label = c(" After drinking the potion, any magic spells or magic-like abilities have bizarre side-affects (GM's decision) for DICE days.", 
    " After drinking the potion, the character can only speak gibberish for DICE hours.", 
    " After drinking the potion, the drinker cannot bear to eat one type of food (DM's choice) for 24 Hours", 
    " After drinking the potion, the drinker cannot use any magic spells or magic-like abilities for DICE hours.", 
    " After drinking the potion, the drinker gets a nasty rash all over her body.", 
    " After drinking the potion, the drinker grows a small tail (Gm's decision what kind) This tail lasts DICE weeks, then falls off without harming the drinker.", 
    " After drinking the potion, the drinker is seized with an irresistible urge to strip totally naked and stack up all clothes, armor, and weapons in a nice, neat bundle.", 
    " After drinking the potion the drinker is struck blind for DICE hours", 
    " After drinking the potion, the drinker is struck mute for DICE hours.", 
    " After drinking the potion the drinker's tongue grows DICE' longer, making speech, spell-casting, and kissing next to impossible for DICE days.", 
    " After the potion has been drank, a blast of steam blasts out of the drinker's ears accompanied by a horribly loud whistling noise. Neither the steam, nor the whistle harms the drinker.", 
    " After the potion has been drank, for DICE hours afterward the drinker may only communicate in the loudest voice possible", 
    " After the potion has been drank, the drinker is magically compelled to eat a large slab of raw meat at the first chance she gets.", 
    " After the potion has been drank, writing appears on the drinker’s tongue (Gm’s decision what it says) it goes away DICE hours later", 
    " After the potion has been drunk, the drinker is driven mad with lust and is compelled to do terrible and naughty things with the next \"compatible\" person (or thing) she comes across.", 
    " After the potion is drank, a live (1d6) 1) snake 2)frog/ toad 3)hamster 4)mouse/rat 5)lizard 6)tiny gorilla wriggles it's way out of the drinker's throat, and forces it's way out of her mouth, jumps out and scurries away.", 
    " After the potion is drank, a pretty flower grows out the drinker's head. This flower does not harm the drinker at all.", 
    " After the potion is drank, one of the character’s most prized and/or important possessions sprouts tiny wings and flutters around the character. It cannot be caught for at least DICE minutes, after which the wings disappear.", 
    " After the potion is drank, the drinker releases a thunderously loud belch", 
    " After the potion is drank, the drinkers voice becomes high pitched and squeaky (As if he just inhaled helium) for DICE minutes", 
    " For DICE days after drinking the potion the drinker is compelled to refer to herself in the third person.", 
    " For DICE days after drinking the potion the drinkers hair becomes spiky and turns golden yellow, his eyes glow bluish-green and she is surrounded by a golden glow.", 
    " For DICE days after drinking the potion, the drinkers skin turns to a sickly greenish-gray pallor, her eyes get all bleary and milky, animals will avoid her, and she carries a rotten stench like an undead.", 
    " For DICE hours after drinking the potion, the drinker gives of an odor that enrages one type of creature (Gm's decision)", 
    " For DICE hours after drinking the potion, when speaking, the character can only say her name in varying emotional tones (like a Pokemon)", 
    " For DICE minutes after the potion is drank, super-powerful COLOR colored beams of light come out of the drinker's eyes. The beams of light are harmless to the drinker or anyone else.", 
    " For DICE Minutes after the potion is drunk, the drinker is compelled to scream uncontrollably.", 
    " For DICE minutes, everything the character says appears on large pieces of paper above her head, painted in large, bold letters.", 
    " The character refers to herself in the third person for DICE days after it is drank.", 
    " The character’s eyes become like those of an animal (GM's decision)", 
    " The character suffers from a massive sneezing fit for DICE minutes (during which she can take NO action).", 
    " The character uncontrollably foams at the mouth a frothy COLOR colored foam for DICE hours.", 
    " The drinker of the potion foams uncontrollably at the mouth for DICE hours.  The foam is COLOR in color.", 
    " The drinker of the potion is plagued by overly friendly kittens for DICE days.", 
    " The drinker of the potion is plagued by overly friendly puppies for DICE days.", 
    " The drinker's skin takes on an woodlice texture, while her hair turns to a mass of leaves (still retaining their usual color) this effect lasts DICE hours.", 
    " The drinker's voice becomes an incredibly low, deep bass for DICE days", 
    " The potion causes nausea", " The potion contains hundreds of tiny, living organisms that swim about.", 
    " The potion continuously changes color between DICE colors: COLOR.", 
    " The potion foams heavily, like root beer when uncorked.", 
    " The potion gives off heat", " The potion glows.", " The potion has a holographic image inside it that always appears right side up. It is of a…(1d10) 1)human face 2)bat 3)octopus 4)brain )5butterfly 6)spider 7)hand 8)snake 9)dragon 10)skull", 
    " The potion has a metallic sheen to it", " The potion has a piece of decaying matter of an unknown type floating in it.", 
    " The potion has a small preserved worm floating in it.", 
    " The potion has a thick layer of sediment at the bottom. In order for the potion to be effective it must be shaken to blend the sediment into the potion.", 
    " The potion has COLOR-colored swirls.", "The potion has COLOR polka dots.ispolka-dottaed", 
    " The potion has small, spherical COLOR-colored objects floating in it.", 
    " The potion has small squiggly COLOR-colored objects floating in it.", 
    " The potion is alcoholic", " The potion is always cold.", 
    "The potion is diluted and is %50 as effective as usual.", 
    "The potion is extra-concentrated and works %50 better than usual.", 
    " The potion is filled with pulp", " The potion is has bits of crystallized matter stuck to the container (like Aftershock or Avalanche)", 
    " The potion is highly unstable. If it is severely jostled it will explode.  Damage is dealt as fire damage equal to that of magic missile from a level DICE wizard.", 
    " The potion is mildly toxic. Drinking it makes the caster ill for DICE hours.", 
    " The potion is sparkly", " The potion is striped like a candy cane, with MAINCOL and COLOR stripes.", 
    " The potion is striped like a zebra, with MAINCOL and COLOR stripes.", 
    " The potion is tainted with The Stupids: a disease. For DICE hours after the potion is drank, The drinker acts like a total ninny, with no wisdom whatsoever.", 
    " The potion is totally opaque (nothing can be seen through the potion)", 
    " The potion is two colors, MAINCOL and COLOR, split right down the middle horizontally.", 
    " The potion is two colors, MAINCOL and COLOR, split right down the middle vertically.", 
    " The potion is unusually spicy. When it is drunk, the drinker belches a small burst of harmless, COLOR colored flame.", 
    " The potion makes the drinker’s hair grow DICE’", " The potion makes the drinker unusually flatulent for DICE hours", 
    " The potion makes the user very sleepy", " The potion permanently changes the drinker's eyes to COLOR in color.", 
    " The potion permanently changes the drinker's hair to COLOR in color.", 
    " The potion puts the drinker to sleep for DICE hours", " The potion releases a blood curdling scream when uncorked", 
    " The potion releases a bout of hideous laughter when uncorked", 
    " The potion releases weird COLOR vapors.", " The potion rumbles, and spews small, dark clouds which fire off harmless miniature lightning bolts and then vanish.", 
    " The potion seems to have a coin or other small, valuable object floating around in it. This is only an illusion and the object disappears when the potion is emptied", 
    " The potion smells of SMELL.", " The potion softly pulses in rhythm like a heart", 
    " The potion sparks and gives off bursts of static electricity", 
    " The potion turns the drinker's hair tartan for DICE hours.", 
    " The potion turns the drinker's skin tartan for DICE hours.", 
    " The potion, when drank makes the user smell of SMELL.", 
    " When drank, the potion will permanently turn the drinker’s hair COLOR in color.", 
    " When drank, the potion will permanently turn the drinker’s skin COLOR in color.", 
    " When looked at the right way, the potion seems to have a face that silently mocks the holder.", 
    " When the liquid of the potion is potion is looked through, everything seems twisted, demonic, and surreal", 
    " When the potion has been drunk, the drinker belches forth clouds of rainbow colored bubbles for DICE minutes.", 
    " When the potion has been drunk, the drinker glows, brightly for DICE hours.  The glow is COLOR in color.", 
    " When the potion has been drunk , the drinker is stuck deaf for DICE hours.", 
    " When the potion has been drunk, the drinker's head is lit on fire by a COLOR-colored flame, while this fire does no damage to the drinker, it does burn of all her hair, and effects other flammable objects normally. This fire lasts DICE minutes and can not be extinguished by normal means.", 
    " When the potion is drank, all of the hair on her body falls out. It then grows back normally.", 
    " When the potion is drank, for 1d6 hours, she attracts small, harmless…(1d6) 1) snakes 2)frogs/ toads 3)flies 4)mice/rats 5)spiders 6)wombats", 
    " When the potion is drank, it makes him hiccup uncontrollably for DICE hours", 
    " When the potion is drank, the drinker is struck with ravenous hunger.", 
    " When the potion is drank, the potion alters the drinker's smell so she smells delicious to monsters for DICE hours.", 
    " When the potion is drunk, the drinker is struck with ravenous thirst.", 
    " When the potion is uncorked it releases a huge cloud of COLOR-colored vapor with a radius of 15'.", 
    " When the potion is uncorked, it releases a puff of vapor that resembles a …(1d10) 1) skull 2)butterfly 3)spider 4)screaming humanoid face 5)laughing humanoid face 6)hand 7)bird 8)bat 9)flower 10) clenched humanoid fist", 
    " When the potion is uncorked it softly speaks unintelligible nonsense.", 
    " When the potion is uncorked, it speaks aloud, giving the characters an important piece of information or advice, but it stops just as it's getting to the important part.", 
    " When uncorked, the potion gives off a short but loud whistle like a teapot", 
    " When uncorked, the potion releases a small, harmless burst of COLOR-colored fire."
    ), class = "factor"), Extra.Options = c(NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA), Extra.Dice = structure(c(7L, 
    5L, 7L, 13L, 1L, 6L, 1L, 7L, 1L, 7L, 1L, 12L, 1L, 6L, 1L, 
    7L, 1L, 14L, 1L, 2L, 4L, 5L, 5L, 7L, 7L, 7L, 7L, 8L, 7L, 
    6L, 3L, 1L, 12L, 1L, 9L, 3L, 7L, 1L, 11L, 11L, 1L, 1L, 1L, 
    2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 11L, 14L, 
    1L, 1L, 1L, 1L, 9L, 1L, 1L, 1L, 1L, 5L, 7L, 1L, 1L, 1L, 7L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 7L, 7L, 1L, 1L, 1L, 1L, 1L, 
    7L, 10L, 7L, 4L, 1L, 7L, 7L, 1L, 9L, 1L, 1L, 1L, 2L, 1L, 
    1L, 1L, 1L, 1L), .Label = c("", "1d10", "1d12", "1d20", "1d3", 
    "1d4", "1d6", "1d8", "2d12", "2d20", "2d4", "2d6", "3d12", 
    "3d6"), class = "factor"), Extra.Color = structure(c(1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 1L, 1L, 2L, 1L, 1L, 
    1L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 3L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 1L, 2L, 2L, 
    1L, 1L, 2L, 2L, 2L, 1L, 1L, 1L, 2L, 2L, 1L, 1L, 1L, 2L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 1L, 1L, 1L, 1L, 2L, 2L, 
    1L, 1L, 1L, 1L, 1L, 1L, 2L, 1L, 1L, 1L, 1L, 2L, 1L, 1L), .Label = c("", 
    "1", "var"), class = "factor"), Extra.Smell = c(NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, 1L, NA, NA, 1L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA)), .Names = c("Taste", 
"Container", "Label", "Label.Language", "Color", "Extra", "Extra.Options", 
"Extra.Dice", "Extra.Color", "Extra.Smell"), class = "data.frame", row.names = c(NA, 
-105L))



.__item_furnishings <-
structure(list(Itemtype = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 4L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 4L, 
1L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 3L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 3L, 1L, 1L, 
1L), .Label = c("", "piece", "square foot", "square yard"), class = "factor"), 
    Furnishings = structure(c(24L, 53L, 14L, 43L, 25L, 54L, 1L, 
    2L, 27L, 33L, 37L, 3L, 4L, 5L, 26L, 55L, 6L, 7L, 28L, 34L, 
    38L, 11L, 12L, 8L, 29L, 39L, 9L, 35L, 40L, 13L, 10L, 30L, 
    41L, 18L, 19L, 21L, 22L, 15L, 17L, 47L, 48L, 23L, 16L, 31L, 
    36L, 42L, 44L, 20L, 51L, 45L, 46L, 49L, 50L, 32L, 52L), .Label = c("4'x 1'x 5' Metal Bookcase", 
    "4'x 1'x 5 Wooden Bookcase", "Buffet ", "Cabinet ", "Carpet ", 
    "Chandelier ", "Chest of drawers ", "Copper Cutlery", "Crystal Decanter", 
    "Crystal Goblet", "Curtains/drapes ", "Cushion ", "Desk ", 
    "Double Bed", "Feather Double Mattress", "Feather Pillow", 
    "Feather Single Mattress", "Hamper ", "Iron Kettle", "Large Rug", 
    "Loom ", "Mat ", "Mirror ", "Padded Armchair", "Padded Bench", 
    "Padded Chair", "Pewter Bowl", "Pewter Cup", "Pewter Cutlery", 
    "Pewter Goblet", "Pewter Plate", "Plain Wardrobe", "Pottery Bowl", 
    "Pottery Cup", "Pottery Decanter", "Pottery Plate", "Silver Bowl", 
    "Silver Cup", "Silver Cutlery", "Silver Decanter", "Silver Goblet", 
    "Silver Plate", "Single Bed", "Small Rug", "Sofa", "Stool ", 
    "Straw Double Mattress", "Straw Single Mattress", "Table ", 
    "Tub ", "Wall Sconce", "Wardrobe with mirrors ", "Wooden Armchair", 
    "Wooden Bench", "Wooden Chair"), class = "factor"), Cost = c(3L, 
    1L, 8L, 5L, 4L, 2L, 15L, 5L, 2L, 5L, 9L, 7L, 4L, 5L, 2L, 
    1L, 20L, 6L, 2L, 4L, 2L, 3L, 1L, 1L, 2L, 5L, 10L, 3L, 5L, 
    15L, 4L, 4L, 2L, 8L, 4L, 6L, 15L, 4L, 2L, 3L, 1L, 12L, 2L, 
    8L, 8L, 2L, 1L, 3L, 5L, 30L, 3L, 2L, 4L, 15L, 25L), Unit = structure(c(3L, 
    3L, 3L, 3L, 3L, 3L, 3L, 3L, 4L, 1L, 3L, 3L, 3L, 1L, 3L, 3L, 
    3L, 3L, 4L, 1L, 2L, 4L, 4L, 4L, 4L, 3L, 3L, 1L, 3L, 3L, 3L, 
    4L, 2L, 1L, 3L, 3L, 1L, 3L, 3L, 3L, 3L, 3L, 4L, 4L, 1L, 3L, 
    4L, 4L, 1L, 3L, 3L, 4L, 3L, 3L, 3L), .Label = c("cp", "ep", 
    "gp", "sp"), class = "factor"), Weight = c(40, 30, 150, 90, 
    20, 15, 250, 100, 1.5, 1.5, 1.5, 5, 80, 2, 25, 18, 30, 70, 
    0.5, 0.4, 0.5, 1, 1, 0.5, 0.5, 0.5, 6, 5.5, 6, 35, 1, 1, 
    1, 4, 2, 200, 5, 30, 20, 25, 15, 2, 1.5, 0.7, 0.6, 0.7, 5, 
    50, 5, 75, 8, 5, 10, 50, 85)), .Names = c("Itemtype", "Furnishings", 
"Cost", "Unit", "Weight"), class = "data.frame", row.names = c(NA, 
-55L))



.__item_clothing <-
structure(list(Gentype = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L), .Label = c("", "square yard"), class = "factor"), Clothing = structure(c(2L, 
3L, 24L, 25L, 32L, 33L, 39L, 4L, 37L, 7L, 8L, 19L, 9L, 20L, 6L, 
16L, 30L, 42L, 47L, 55L, 56L, 17L, 22L, 5L, 35L, 10L, 29L, 14L, 
11L, 21L, 49L, 26L, 48L, 27L, 28L, 31L, 34L, 44L, 36L, 38L, 15L, 
18L, 40L, 41L, 43L, 45L, 46L, 50L, 51L, 52L, 1L, 13L, 53L, 54L, 
12L, 23L), .Label = c(" 1 spool Thread", " Apron ", " Belt ", 
" Breeches ", " Broad Girdle", " Canvas Cloth", " Cap ", " Cloth Cape", 
" Cloth Cloak", " Cloth Gloves", " Cloth Hat", " Cloth Vest", 
" coarse Toga", " Common Gown", " Common Robe", " Cotton Cloth", 
" Dress ", " Embroidered Robe", " Fur Cape", " Fur Cloak", " Fur Hat", 
" Fur trimming ", " Fur Vest", " High Hard Boots", " High Soft Boots", 
" Hose/Leggings ", " Jerkin ", " Knife Sheath ", " Leather Gloves", 
" Linen Cloth", " Loincloth ", " Low Hard Boots", " Low Soft Boots", 
" Mittens ", " Normal Girdle", " Pin ", " Plain Brooch", " Poor Robe", 
" Riding Boots", " Sandals ", " Sash ", " Satin Cloth", " Scissors ", 
" Sewing Needle", " Shirt/blouse ", " Shoes ", " Silk Cloth", 
" Silk Jacket", " Straw Hat", " Surcoat ", "  Sword Scabbard", 
" Tabard ", " Trouser/skirt ", " Tunic ", " Velvet Cloth", " Wool Cloth"
), class = "factor"), Cost = structure(c(1L, 9L, 6L, 1L, 1L, 
16L, 9L, 6L, 2L, 1L, 9L, 3L, 6L, 8L, 1L, 1L, 12L, 10L, 2L, 10L, 
16L, 18L, 2L, 9L, 6L, 5L, 13L, 4L, 2L, 11L, 15L, 6L, 17L, 1L, 
9L, 1L, 9L, 6L, 1L, 14L, 18L, 7L, 12L, 1L, 12L, 10L, 1L, 14L, 
10L, 14L, 14L, 16L, 9L, 16L, 1L, 3L), .Label = c("1", "10", "100", 
"12", "1-2", "2", "20", "200", "3", "4", "40", "5", "5-10", "6", 
"7", "8", "80", "9"), class = "factor"), Unit = structure(c(2L, 
5L, 3L, 3L, 3L, 4L, 3L, 3L, 3L, 4L, 2L, 3L, 4L, 3L, 3L, 2L, 1L, 
3L, 3L, 3L, 1L, 2L, 3L, 3L, 3L, 2L, 3L, 4L, 2L, 3L, 1L, 3L, 3L, 
3L, 2L, 2L, 4L, 4L, 3L, 2L, 4L, 3L, 2L, 3L, 2L, 2L, 3L, 4L, 3L, 
4L, 1L, 2L, 2L, 4L, 3L, 3L), .Label = c("bp", "cp", "gp", "sp", 
"Sp"), class = "factor"), Weight = c(1, 0.3, 7, 5, 5, 3, 6, 1, 
0.2, 1, 1, 2, 2, 3, 2, 1, 1, 1, 0.5, 1, 2, 4, 0.1, 1, 0.5, 0.5, 
1, 2, 1, 1, 0.5, 0.5, 1, 7.5, 0.5, 0.5, 0.5, 0.1, 0.1, 5, 5, 
5, 1, 0.5, 1, 1, 1, 1, 1, 1, 0.5, 1, 1, 1, 1, 1.5)), .Names = c("Gentype", 
"Clothing", "Cost", "Unit", "Weight"), class = "data.frame", row.names = c(NA, 
-56L))



.__item_provisions <-
structure(list(Itemtype = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 3L, 1L, 1L, 4L, 1L, 1L, 1L, 4L, 1L, 1L, 2L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 5L, 5L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), .Label = c("", "day of", 
"days of ", "pound bag of ", "week of"), class = "factor"), Provisions. = structure(c(20L, 
25L, 30L, 31L, 22L, 16L, 2L, 23L, 47L, 7L, 9L, 8L, 10L, 11L, 
43L, 1L, 12L, 17L, 41L, 14L, 29L, 6L, 21L, 28L, 33L, 37L, 32L, 
24L, 26L, 18L, 39L, 15L, 45L, 40L, 34L, 44L, 42L, 4L, 13L, 19L, 
3L, 5L, 36L, 35L, 27L, 46L, 38L), .Label = c(" Barrel of Pickled Fish", 
" Butter", "Cinnamon Spice", "Clove Spice", " Coarse (lb) Sugar", 
" Common herbs", " Dry Rations", " Eggs (12) ", " Eggs (50) ", 
" Figs", " Firewood (day) ", "Flour", "Ginger Spice", " Horse meal Grain", 
"Iron Rations", " loaf of Bread", " Merchant's meal Food", " Nuts (lb) ", 
"Pepper Spice", "pint of Ale", " Pint of Apple Juice", " pint of Brandy", 
" pint of Cider", " Pint of Cow Milk", "pint of dark Ale", " Pint of Goat Milk", 
" Pint of Good Wine", " Pint of Grape Juice", " Pint of Grog", 
"pint of heavy Beer", "pint of light Beer", " Pint of Mead", 
" Pint of Orange Juice", " Pint of Rum", " Pint of Spring Water", 
" Pint of Tea", " Pint of Tomato Juice", " Pint of Watered Wine", 
" Raisins (lb) ", " Rice (lb) ", " Rich meal Food", "Saffron Spice", 
" Salted Herring Fish", " Salt (lb) ", "Standard Rations", " Tun (250 Gal) Good Wine", 
" Tun (250 ga) of Cider"), class = "factor"), Cost. = c(1L, 3L, 
1L, 4L, 1L, 7L, 2L, 8L, 8L, 10L, 7L, 2L, 3L, 1L, 1L, 3L, 6L, 
1L, 1L, 1L, 3L, 5L, 8L, 8L, 9L, 7L, 5L, 2L, 1L, 1L, 2L, 5L, 3L, 
2L, 5L, 1L, 15L, 15L, 2L, 2L, 1L, 5L, 7L, 5L, 1L, 20L, 6L), Unit = structure(c(2L, 
2L, 4L, 2L, 4L, 1L, 4L, 2L, 2L, 3L, 4L, 4L, 4L, 2L, 4L, 3L, 4L, 
4L, 3L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 4L, 4L, 3L, 3L, 
4L, 2L, 4L, 3L, 3L, 3L, 3L, 3L, 4L, 1L, 1L, 4L, 3L, 2L), .Label = c("bp", 
"cp", "gp", "sp"), class = "factor"), Weight = c(0, 0, 0, 0, 
0, 2.5, 1, 0, 2050, 1, 0, 0, 1, 5, 0, 0, 1, 0, 0, 5, 0, 1, 0, 
0, 0, 0, 0, 0, 0, 1, 1, 7.5, 20, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 
0, 0, 2050, 0)), .Names = c("Itemtype", "Provisions.", "Cost.", 
"Unit", "Weight"), class = "data.frame", row.names = c(NA, -47L
))
